### ISSUE TITLE
CSS setup

### ISSUE THREAD

**Issue by ngscheurich** [BatonRougeTech/BRTechWebsite#6]
@james-alt @isralduke Do y'all have an idea of the styling paradigm we should use here—styled components, CSS files, or some combination thereof?

What about pre/post-processing? I tend to prefer PostCSS, but I'm open to whatever.

**Comment by james-alt** [comment]
I don't do a lot of react/gatsby, it just seemed like the most welcoming environment for the most groups in my opinion so I will defer to others with more knowledge in this space.

**Comment by QuintonJason** [comment]
CSS files with PostCSS or Sass

**Comment by ngscheurich** [comment]
I was leaning towards CSS files with PostCSS, so unless anyone has a different opinion, I'll move forward with that.

**Comment by james-alt** [comment]
Sounds good. Open a PR and let’s see what it looks like.

**Comment by QuintonJason** [comment]
I'll start one later today. I have a folder structure in mind.

**Comment by ngscheurich** [comment]
We're collabing on this in #13.
